# Site settings
title: Walk In Tour
description: Once upon a time
keywords: Viajes, Angel, Teresa
author: Angel Muelas y Teresa Librero
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://walkintour.github.io/" # the base hostname & protocol for your site
