# Site settings
title: Aurore & Gérard
description: Once upon a love
keywords: Mariage, Aurore, Gérard
author: Aurore et Gérard
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://walkintour.github.io/" # the base hostname & protocol for your site